### ISSUE TITLE
用户信息数据和接口文档不符

### ISSUE THREAD

**Issue by LipYoung** [slimkit/thinksns-plus#108]
thinksns-plus/docs/api/v2/user/followers.md
该文档描述的接口返回字段和实际返回字段不一致

**Comment by medz** [comment]
哦
在 2017年7月26日，10:02，Lip Young <notifications@github.com<mailto:notifications@github.com>> 写道：


thinksns-plus/docs/api/v2/user/followers.md
该文档描述的接口返回字段和实际返回字段不一致

**Comment by LipYoung** [comment]
哦你妹啊，处理啊
