### ISSUE TITLE
建议： 扩展包菜单，iframe组件，路由增强

### ISSUE THREAD

**Issue by lain1936** [slimkit/thinksns-plus#114]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:
在iframe里单页交互后，iframe的地址会变化，但是F5刷新后，主框架依然是loadManageFrom注册的首页地址

在iframe组件加载时标记是否首次加载，尝试读取/比较/缓存 this.$refs.iframe.contentWindow.location.href ，设置src

load事件应该可以监听地址改变
`<iframe ref="iframe" src="child.html" @load="loaded"></iframe>

loaded() {
    const vm = this.$refs.iframe.contentWindow.vm
    console.log(vm)
    //vm.func1()
}
`

ps.  扩展包菜单地址语义化
octobercms后台也是扩展包注册菜单，只是菜单结构和前端展示架构不同， 不过扩展包很容易就超过10个.  感觉plus的扩展包数量也容易加到很多，如果多了，浏览器地址栏用数字的话没那么好识别和分享地址（虽然大多没人去记，分享也没多大意义）， 不过可以考虑支持用auth_name/package_name注册菜单地址，  package[/vendor]/auth_name/package_name  （不过也有吐槽说 用auth_name这种也不爽的，但又怕命名冲突）

### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
建议很好。
