### ISSUE TITLE
后台管理-用户中心不显示任何账号

### ISSUE THREAD

**Issue by 1377195627** [slimkit/thinksns-plus#116]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

后台管理-用户中心不显示任何账号
![image](https://user-images.githubusercontent.com/8142265/28859189-9a21565e-771b-11e7-9cc8-ffc96a1f66ad.png)

**Comment by medz** [comment]
已修复，单不打包允许文件。到下一个 tag 时候上传。
