### ISSUE TITLE
[系统通知] 文档不完成,导致无法解析

### ISSUE THREAD

**Issue by LipYoung** [slimkit/thinksns-plus#132]
https://github.com/slimkit/thinksns-plus/blob/master/docs/zh-CN/api2/notifications.md

该文档的 未读通知数量检查  接口.未注明 data.channel 会导致 data.extra .

同时未注明 data.channel 对应的data 类型,导致无法解析

**Comment by boxshadow** [comment]
@this-BaiShi 给他个全家桶

**Comment by this-BaiShi** [comment]
已给出，后续通知类型将陆续更新
[通知](https://github.com/zhiyicx/thinksns-plus-document/blob/master/Summary/notifications.md)
