### ISSUE TITLE
获取验证码无法用来做账号绑定

### ISSUE THREAD

**Issue by Jungle68** [slimkit/thinksns-plus#133]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

用注册方式拿不到验证码；
用非注册拿到验证码，
提示验证码错误或者失效

### Fixed step:

- [ ] fixed.

**Comment by this-BaiShi** [comment]
- 修复绑定接口逻辑判断问题
- 已沟通：绑定接口使用注册验证码，解绑接口使用非注册验证码
