### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by ivantree** [slimkit/thinksns-plus#137]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:
安装出错

PS C:\xampp\webroot\thinksns> php artisan migrate

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Parse error: syntax error, unexpected '$table' (T_VARIABLE)

**Comment by medz** [comment]
能给出具体错误吗？ 执行 `php artisan migrate -vvv` 然后错误信息截图下，或者使用 markdown 发出来一下。感谢。
