### ISSUE TITLE
安装成功后登录后台失败

### ISSUE THREAD

**Issue by luozhanxin** [slimkit/thinksns-plus#138]
- TS+ Version: v1.0.0
- PHP Version: 7.0.2
- Database Driver & Version:1.12.6

### Description:

安装成功后登录后台显示反射错误，无法找到APP/User

(1/1) ReflectionExceptionClass App\User does not exist
--
in Container.php (line 729)
at ReflectionClass->__construct('App\\User')in Container.php (line 729)
at Container->build('App\\User')in Container.php (line 608)
at Container->resolve('App\\User')in Container.php (line 575)
at Container->make('App\\User')in Application.php (line 728)
at Application->make('App\\User')in JWTAuthServiceProvider.php (line 124)
at JWTAuthServiceProvider->Tymon\JWTAuth\Providers\{closure}(object(Application), array())in Container.php (line 726)

### Fixed step:
安装后登录后台
- [x] fixed.

**Comment by medz** [comment]
你是不是运行了 `php artisan vendor:publish --force` ? 如果是，之后请不要加入 `--force` 参数，补救方法运行 `git checkout config` 即可。

**Comment by medz** [comment]
`--force` 参数是强制覆盖已发布的配置以及其他资源，而配置是不需要被覆盖的，我们已将第三方需要的配置配置好了的。

**Comment by luozhanxin** [comment]
好的。。多谢啦，问题已经解决了。。
