### ISSUE TITLE
用户信息缺少认证信息，或则给出单独的接口

### ISSUE THREAD

**Issue by Jungle68** [slimkit/thinksns-plus#139]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

个人主页需要显示用户认证信心

### Fixed step:

- [ ] fixed.

**Comment by this-BaiShi** [comment]
获取当前用户信息时已有认证信息字段

**Comment by Jungle68** [comment]
@this-BaiShi 老铁，看看description啊，你们现在就放回登录type跟icon 认证描述等内容呢？

**Comment by this-BaiShi** [comment]
了解~
