### ISSUE TITLE
"Class App\User does not exist"

### ISSUE THREAD

**Issue by XuYS** [slimkit/thinksns-plus#143]
- TS+ Version: v#.#.#
- PHP Version:7.0.8
- Database Driver & Version:  5.5.42

### Description:
本地系统是Mac OS。
祖传安装方法安装的。到第五步数据填充php artisan db:seed，登录页面都没问题。但是登录提交以后就出现
```
ReflectionException (-1)
Class App\User does not exist
```
怎么解决呢？

### Fixed step:

- [x] fixed.

**Comment by XuYS** [comment]
发布资源 的时候选择了 发布所有可发布的，所以把官方的  config/jwt.php 给改了， 把这个文件复原就可以了~

**Comment by medz** [comment]
嗯，我们会在安装说明中注意此项。
