### ISSUE TITLE
执行命令php artisan migrate 报错

### ISSUE THREAD

**Issue by 1459416736** [slimkit/thinksns-plus#145]
- TS+ Version: 最新版本
- PHP Version:7.1
- Database Driver & Version:mysql5.7

### Description:
执行命令php artisan migrate 
报错: Call to undefined method Zhiyi\Plus\Console\Kernel::load

**Comment by medz** [comment]
你是不是没执行 composer update 呢，哈哈，框架已升级到 laravel 5.5。你执行下。

**Comment by 1459416736** [comment]
嗯，对的，thanks
