### ISSUE TITLE
建议增加手机识别功能，这样更加有利于Bug的反馈和排查。

### ISSUE THREAD

**Issue by itb10why** [slimkit/thinksns-plus#147]
Such as title.

**Comment by medz** [comment]
感谢建议，我觉得这是一个很不错的建议，我指定给移动端头子。看是否可行。

**Comment by itb10why** [comment]
反馈的问题，官方老是问，手机型号是什么？这个对于技术大牛而言，简直就是小菜一碟。在微博区，可以设置一个参数，获取用户手机型号。在sina微博中，也是早已使用且一直在使用的做法。

**Comment by medz** [comment]
我觉得直接增加错误报告机制更好，发生问题 app 弹出报告界面，用户添加简单描述问题，点击提交按钮，然后连同  log 一并发到服务器上。

**Comment by itb10why** [comment]
那是您的需求。但是TS社区的用户需求是发帖发微博，也是刷存在感，体验APP。把用户喜欢做的事情，和您的需求对接起来，这就是巧妙的。
真正一个错误报告机制，那是GitHub上做的事情。一般用户不会专门给您报告错误哦。

**Comment by medz** [comment]
我指的是测试版增加。

**Comment by itb10why** [comment]
嗯，您定。

**Comment by medz** [comment]
哈哈，具体要不要做还得看移动端的，
