### ISSUE TITLE
一个问题只能回答一遍吗？NO，我可以回答N个，请看下面

### ISSUE THREAD

**Issue by itb10why** [slimkit/thinksns-plus#150]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

![screenshot_2017-09-15-00-32-02](https://user-images.githubusercontent.com/29001750/30467906-79663854-9a1a-11e7-88af-74344e69d50b.jpg)

### Steps To Reproduce:

回答完以后，返回的页面，添加回答并没有刷新。
第二次准备回答的时候，显然没有检查我是否已经回答一次。

### Fixed step:

- [ ] fixed.

**Comment by itb10why** [comment]
@medz

**Comment by medz** [comment]
是可以回答多次的～

**Comment by medz** [comment]
逻辑是这样的，一对一悬赏，第一次回答作为回答的答案，并获得悬赏，然后的规则就是用户可所以回答，可以多个回答。

**Comment by itb10why** [comment]
不要想着钱。应该是回答的条理性。这样的回答方式类似于灌水了。
可回答，可以编辑回答。可以更新回答。
但是一个人只能回答一次。不断完善一个高质量的回答。

**Comment by medz** [comment]
这个和钱无关，用户确实可以添加多个回答，这个是产品需求。之前我们也想过的。

**Comment by itb10why** [comment]
知乎，quaro，都是这样的做法。看看我刚才随便做的回答。感觉这就是一个很难管理的社区。
建议在后台可以设置。
一人一答，或一人多答2种模式

**Comment by medz** [comment]
这样吧，后台可设置没人可多次回答或者一次回答的，作为建议需求，在 https://github.com/slimkit/plus-question 提一个 issues。下期有时间我们增加这个功能。

**Comment by medz** [comment]
再次感谢建议。

**Comment by zxy198717** [comment]
@medz https://github.com/slimkit/plus-question  问答模块不开源了吗？
