### ISSUE TITLE
【PC】快速点击导航栏，group 和 new 都会出现页面显示报错信息。

### ISSUE THREAD

**Issue by itb10why** [slimkit/thinksns-plus#151]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

![v8d q 8 drsgatmyygk4 bx](https://user-images.githubusercontent.com/29001750/30468167-4ab86110-9a1c-11e7-916b-2d8dbffcf955.png)

![izu jo 1 mq6weigklhln](https://user-images.githubusercontent.com/29001750/30468221-89a66b06-9a1c-11e7-8a13-07e5d0e0182f.png)

### Steps To Reproduce:

QQ浏览器，点击快一些，就会如此
### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
网址是？

**Comment by medz** [comment]
@HHHCODE pc 的 bug。

**Comment by HHHCODE** [comment]
@medz 线上晚点更，在dev上测试

**Comment by HHHCODE** [comment]
@medz 线上晚点更，在dev上测试

**Comment by medz** [comment]
@HHHCODE tsplus.zhibocloud.cn/group

**Comment by itb10why** [comment]
http://tsplus.zhibocloud.cn/group 等 只要在一个页面请求发出后，没有完全加载的时候。随意去点击其他的页面，就容易出现

**Comment by medz** [comment]
@HHHCODE 
![image](https://user-images.githubusercontent.com/5564821/30468360-7c2b9e3c-9a1d-11e7-8f8a-b6b14bc9a7d9.png)
快速点击导航来回切换，确实出现了。

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/30468386-983acb84-9a1d-11e7-9cfd-0029afaf1430.png)
两个之间快速切换。

**Comment by itb10why** [comment]
好产品，就是需要经历这样的蹂躏。

**Comment by itb10why** [comment]
你能够修改我的问题，因为您觉得我的问题不够精准。其实TS+中的问题，应该也这样的。问题的公共编辑，请考虑
@medz

**Comment by itb10why** [comment]
很多时候，提一个好的问题【话题】，比回答一个问题更难。不是么

**Comment by medz** [comment]
哈哈，我修改你的问题 title 只是为了方便其他人遇到同样问题能够搜索参阅以及开发人员更快的识别，不是为了别的哈，别误会。一个好的问题 title 往往比详细的内容更重要，因为看见问题第一眼，如果能从 title 中就大概知道问题是啥，也是一门艺术。

**Comment by itb10why** [comment]
我的意思是TS+的问答功能中，有没有问题的公共编辑功能。
比如好友，或者管理员可以对问题进行完善。这样的话，有助于提高整个社区的内容质量。Quaro就是这样的。
“一个好的问题 title 往往比详细的内容更重要，因为看见问题第一眼，如果能从 title 中就大概知道问题是啥，也是一门艺术。”
