### ISSUE TITLE
【PC】用户链接失效，点击无法操作查看用户页

### ISSUE THREAD

**Issue by itb10why** [slimkit/thinksns-plus#152]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

QQ浏览器
![q348 suzlb7wpu3rg6fe0](https://user-images.githubusercontent.com/29001750/30481249-2db7f60a-9a50-11e7-930a-083da4349cb5.png)

可以关注用户
但是无法进入用户页。
点击无反应

### Fixed step:

- [ ] fixed.

**Comment by this-BaiShi** [comment]
已反馈给pc端
