### ISSUE TITLE
安卓，问答功能：已经回答问题后，显示问题

### ISSUE THREAD

**Issue by itb10why** [slimkit/thinksns-plus#153]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

我已经回答问题了！
回答完后的页面是这样的

![screenshot_2017-09-16-15-40-46](https://user-images.githubusercontent.com/29001750/30511647-7d37214a-9b10-11e7-95e8-a4309e0d7a26.png)

1，我并不知道我已经回答成功
2，添加回答，按钮并没人任何变化

直到我下拉刷新后

才恢复显示正常

### Fixed step:

- [ ] fixed.

**Comment by itb10why** [comment]
![screenshot_2017-09-16-15-40-56](https://user-images.githubusercontent.com/29001750/30511844-10b31d0e-9b14-11e7-94b0-ac92b227487b.png)
后面效果如图

**Comment by itb10why** [comment]
建议最新的回答应该默认排在最前面

**Comment by this-BaiShi** [comment]
您好，这个是这样的，我们产品的需求是这里的问答有邀请回答和采纳回答的功能，所以这里列表显示的回答，优先显示被邀请的回答和被采纳的回答

**Comment by itb10why** [comment]
第一是显示问题。刷新动作逻辑要优化
第二是回答的排序设置，建议后台选项【是否采纳最佳回答】【默认排序策略：被采纳的回答、被邀请的回答、最新的回答】

**Comment by this-BaiShi** [comment]
好的，谢谢你的建议和反馈😁
