### ISSUE TITLE
安卓手机端 微博区 功能划分可以更合理

### ISSUE THREAD

**Issue by itb10why** [slimkit/thinksns-plus#154]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

![snnk7 n x1k 1 g _b2o07](https://user-images.githubusercontent.com/29001750/30511909-6f4b0c04-9b15-11e7-80c8-32d1d179c608.png)

如图所示

目前 第3区，操作互动区，划分不是很明显。容易误点进2区，进入微博页面。
点到空白
或者连续点击2次点赞，
或者点到眼睛，都容易~~~

### Fixed step:

- [ ] fixed.

**Comment by this-BaiShi** [comment]
已反馈给移动端这边，谢谢您的建议

**Comment by medz** [comment]
感谢反馈，已产品提出建议。
