### ISSUE TITLE
接口文档未对返回字段进行说明

### ISSUE THREAD

**Issue by LipYoung** [slimkit/thinksns-plus#155]
https://slimkit.github.io/plus-docs/v2/package-feed/pinned#parameters

**Comment by this-BaiShi** [comment]
这个已经在资讯-审核评论置顶部分补充上了，我就关了

**Comment by wang2gou** [comment]
我想问一下，为什么我会受到诸位得技术讨论邮件，我点了什么不该点的东西了吗。




发自二狗哥的网易邮箱大师
在2017年09月18日 10:13，Lip Young 写道：

https://slimkit.github.io/plus-docs/v2/package-feed/pinned#parameters

**Comment by medz** [comment]
@wang2gou 你可以点击仓库左上角的 watch 按钮，选择 「Not Watching」这样就收不到了。
