### ISSUE TITLE
图片存储位置错误

### ISSUE THREAD

**Issue by sucof** [slimkit/thinksns-plus#160]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

图片保存位置错误，不管是在h5中，还是后端管理资讯，图片存储位置应该形如http://url/storage/app/public/2017..../*.jpg，但是实际中缺少app/public，所以找不到

### Fixed step:

加上/app/public

**Comment by this-BaiShi** [comment]
![image](https://user-images.githubusercontent.com/9911791/30945358-6f4b5226-a430-11e7-9097-ae2034a5bb2f.png)
这个在laravel文档上是有的，附件默认在storage下，link到public以供公开访问

**Comment by medz** [comment]
You need read for [https://slimkit.github.io/plus-docs/core/latest/getting-started/installed#目录权限-& 公开资源](https://slimkit.github.io/plus-docs/core/latest/getting-started/installed#目录权限-& 公开资源)
