### ISSUE TITLE
问答模块-答案详情

### ISSUE THREAD

**Issue by legendarytym** [slimkit/thinksns-plus#163]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:
@this-BaiShi 
答案详情的接口没有返回答案的具体内容，该答案是公开答案

### Fixed step:

- [ ] fixed.

**Comment by this-BaiShi** [comment]
已修改

**Comment by legendarytym** [comment]
@this-BaiShi dev 
"question_id": 270, 还有这个问题

**Comment by this-BaiShi** [comment]
我看了一下。。270开启了围观的
