### ISSUE TITLE
mix 解析出错：Undefined index: /js/admin.js

### ISSUE THREAD

**Issue by Romoloso** [slimkit/thinksns-plus#167]
- TS+ Version: v#.#.#
- PHP Version:7.0.9
- Database Driver & Version: 5.7

### Description:
运行`npm run dev`，并刷新页面出现错误提示：

ErrorException (E_ERROR)
Undefined index: /js/admin.js (View: D:\Software\XAMPP\htdocs\slimkit\resources\views\admin.blade.php)

### Steps To Reproduce:
![tim 20171017141747](https://user-images.githubusercontent.com/9602107/31649557-0d48ec8a-b346-11e7-9886-579e7c44da96.png)

### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
图片呢？

**Comment by Romoloso** [comment]
@medz 上传了

**Comment by medz** [comment]
@Romoloso 你运行 npm run dev 的需求场景是啥？貌似你运行过程中报错了。

**Comment by Romoloso** [comment]
@medz 没需求场景啊，我就是按照laravel [runnig-mix](https://laravel.com/docs/5.5/mix#running-mix)这里一步步操作的，

**Comment by medz** [comment]
既然没有，你本身是不需要运行的。。。

**Comment by medz** [comment]
因为我们会定期提供 public 下的静态资源，除非你自己需要修改 resource/assets  下的内容才有运行需求。

**Comment by medz** [comment]
因为这部分是纯前端的东西，不建议不会前端构建的用户自己使用。

**Comment by medz** [comment]
你可以使用运行 `git checkout public` 来恢复。

**Comment by Romoloso** [comment]
@medz 什么也没改，就是单纯的想在浏览器中显示

**Comment by Romoloso** [comment]
@medz 可以了，能进后台了，按照你说的。 谢谢你了

**Comment by medz** [comment]
所以你不需要运行… 合着我说了这么多你都没看我说的。

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2017年10月17日，14:26，Romoloso <notifications@github.com<mailto:notifications@github.com>> 写道：


@medz<https://github.com/medz> 什么也没改，就是单纯的想在浏览器中显示

**Comment by medz** [comment]
那就好 close #167

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2017年10月17日，14:27，Romoloso <notifications@github.com<mailto:notifications@github.com>> 写道：


@medz<https://github.com/medz> 可以了，能进后台了，按照你说的。 谢谢你了
