### ISSUE TITLE
关于完善问答页面内容

### ISSUE THREAD

**Issue by itb10why** [slimkit/thinksns-plus#168]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

![image](https://user-images.githubusercontent.com/29001750/31669700-5ed6eea2-b388-11e7-8ae4-edddd878a482.png)

在这个位置增加 问题 （不需要详细描述）
这才是一个完整的问与答。

点击链接，返回问题-回答list页面。

### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
This is not a requirement for our product manager, thanks for the advice.
