### ISSUE TITLE
test服务器上传图片失败

### ISSUE THREAD

**Issue by legendarytym** [slimkit/thinksns-plus#171]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

没啥好说的，就是传不上大点儿的图片，比如手机拍的。
![image](https://user-images.githubusercontent.com/11835710/31802590-a766ed2a-b581-11e7-9aaa-122882485d98.png)
@this-BaiShi 

### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
请提供图片具体信息，例如体积。

**Comment by this-BaiShi** [comment]
已查明是是服务器配置问题，已修改
