### ISSUE TITLE
app启动信息格式错误

### ISSUE THREAD

**Issue by legendarytym** [slimkit/thinksns-plus#172]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

@this-BaiShi @boxshadow 
![qq 20171020110754](https://user-images.githubusercontent.com/11835710/31803583-23805b80-b587-11e7-8664-862395715a53.jpg)
这里是一个 object , 但返回的是 boolean 类型

### Fixed step:

- [ ] fixed.

**Comment by this-BaiShi** [comment]
已修改
