### ISSUE TITLE
【后台】标签管理-没有标签搜索功能

### ISSUE THREAD

**Issue by peicaichi** [slimkit/thinksns-plus#182]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

![image](https://user-images.githubusercontent.com/22809873/32091776-366a5362-bb28-11e7-9a2c-d32c7462ac05.png)

### Fixed step:

- [ ] fixed.

**Comment by this-BaiShi** [comment]
这个有
