### ISSUE TITLE
【后台】认证用户列表中，无数量统计

### ISSUE THREAD

**Issue by peicaichi** [slimkit/thinksns-plus#184]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

认证用户列表中，全部申请认证用户，已认证用户，待审核用户，驳回用户，无数量统计，及没有展示有多少条数据
### Fixed step:

- [x] fixed.

**Comment by huhaophp** [comment]
已添加

**Comment by medz** [comment]
lable 是用来标示 issue 类型的，不是状态。@huhaophp
