### ISSUE TITLE
【后台】添加认证部分用户搜索不到

### ISSUE THREAD

**Issue by peicaichi** [slimkit/thinksns-plus#185]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

添加认证-系统中存在“智艺哥哥”这个用户名，但是添加认证用户，搜索用户名的时，确搜索不到

### Fixed step:

- [ ] fixed.

**Comment by this-BaiShi** [comment]
这里已查证，是该用户已被认证，搜索用户名只会返回未认证的用户
