### ISSUE TITLE
【后台】过滤词-现在过滤词是有问题的，无法添加类型，无法添加敏感词

### ISSUE THREAD

**Issue by peicaichi** [slimkit/thinksns-plus#186]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

![image](https://user-images.githubusercontent.com/22809873/32093392-b13aeb96-bb2e-11e7-8e51-463fc8afbf91.png)

### Fixed step:

- [x] fixed.

**Comment by huhaophp** [comment]
接口逻辑还需实现
