### ISSUE TITLE
【后台】钱包管理-流水-订单流水检索，增加用户名检索条件

### ISSUE THREAD

**Issue by peicaichi** [slimkit/thinksns-plus#189]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

![image](https://user-images.githubusercontent.com/22809873/32094043-18c89bd0-bb31-11e7-9713-be05008b93fb.png)

### Fixed step:

- [ ] fixed.

**Comment by huhaophp** [comment]
已添加
