### ISSUE TITLE
【后台】音乐管理页面UI未与其他页面统一

### ISSUE THREAD

**Issue by peicaichi** [slimkit/thinksns-plus#192]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

取消掉如图所示地方
![image](https://user-images.githubusercontent.com/22809873/32094776-85fe8366-bb33-11e7-889e-f5241f0fa568.png)

### Fixed step:

- [x] fixed.

**Comment by medz** [comment]
哈哈，确实好丑。
