### ISSUE TITLE
【后台】动态管理--动态统计，根据筛选条件搜索的结果一个条件不符

### ISSUE THREAD

**Issue by maanrry** [slimkit/thinksns-plus#196]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:
根据筛选条件搜索的结果一个条件不符
条件
![image](https://user-images.githubusercontent.com/30249193/32151666-a2a8a05a-bd59-11e7-8e72-d7134b115c81.png)
结果：
![image](https://user-images.githubusercontent.com/30249193/32151674-b9cd3840-bd59-11e7-9bc8-1201ec852f7b.png)

### Fixed step:

- [x] fixed.

**Comment by this-BaiShi** [comment]
这个是前台没有处理时区导致的，显示的时间都为0时区时间
