### ISSUE TITLE
【后台】资讯：表单缺少栏目

### ISSUE THREAD

**Issue by maanrry** [slimkit/thinksns-plus#209]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:
每个表单缺少栏目

![image](https://user-images.githubusercontent.com/30249193/32153368-04d5574a-bd65-11e7-8903-3868ed096e7f.png)

### Fixed step:

- [x] fixed.

**Comment by huhaophp** [comment]
已添加
