### ISSUE TITLE
【后台】问答修改已有的话题提示话题名称已存在导致无法修改

### ISSUE THREAD

**Issue by peicaichi** [slimkit/thinksns-plus#211]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

问答修改已有的话题提示话题名称已存在导致无法修改

### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
😂额～这个是问题呀～修改的话题名称已存在了肯定是改不了的。

**Comment by medz** [comment]
@this-BaiShi 是不是你接口的锅？我觉得 pcc 想说的是输入不存在的话题名称还是提示这个。

**Comment by this-BaiShi** [comment]
![image](https://user-images.githubusercontent.com/9911791/32156422-3c6fb3b8-bd78-11e7-8c01-b511130020d5.png)

说的好像是这个。。。编辑的时候没修改话题名称吧

**Comment by medz** [comment]
@this-BaiShi 那就是你的锅。。。我当时给你说这个的时候就说你要注意下，可能你写出来有这个bug，果然，提示你了你还是把这个bug写出来了。

**Comment by this-BaiShi** [comment]
额。。。。好的

**Comment by medz** [comment]
@this-BaiShi 😄我当时就抽烟去之前给你说的，你可能写出来没有排除当前话题名称，就会提示已存在无法修改，叫你写的时候注意下这个问题😂你还是没注意，写出来了。
