### ISSUE TITLE
【后台】问答模块--精选管理：列表页无总数据展示

### ISSUE THREAD

**Issue by maanrry** [slimkit/thinksns-plus#217]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

列表页无总数据展示
![image](https://user-images.githubusercontent.com/30249193/32154179-e1fcbdbc-bd69-11e7-94e4-ae3ed79fe957.png)

### Fixed step:

- [x] fixed.

**Comment by huhaophp** [comment]
已添加
