### ISSUE TITLE
【后台】问答模块--回答管理：无数据

### ISSUE THREAD

**Issue by maanrry** [slimkit/thinksns-plus#218]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:
无数据
![image](https://user-images.githubusercontent.com/30249193/32154208-139849d6-bd6a-11e7-9938-ca8a9e70d173.png)

### Fixed step:

- [x] fixed.

**Comment by huhaophp** [comment]
已修复
