### ISSUE TITLE
【后台】问答模块--精选管理：筛选条件缺少”类型“

### ISSUE THREAD

**Issue by maanrry** [slimkit/thinksns-plus#220]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:
筛选条件缺少”类型“

![image](https://user-images.githubusercontent.com/30249193/32156499-ce8ae268-bd78-11e7-9d9a-5f50bb15fab1.png)

### Fixed step:

- [x] fixed.

**Comment by huhaophp** [comment]
已修复
