### ISSUE TITLE
【后台】问答模块--精选管理：已经审核通过的问题缺少“撤销精选”、“查看问题/编辑”的按钮

### ISSUE THREAD

**Issue by maanrry** [slimkit/thinksns-plus#221]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:
已经审核过（包括通过和拒绝）的问题和 缺少“撤销精选”、“查看问题/编辑”的按钮

![image](https://user-images.githubusercontent.com/30249193/32156545-17665da0-bd79-11e7-8096-f520daac38f4.png)

### Fixed step:

- [ ] fixed.

**Comment by this-BaiShi** [comment]
问题管理中  已有加精和撤销精选的按钮
