### ISSUE TITLE
【后台】问答模块--话题管理：创建话题缺少话题头像，话题状态（启动、禁用）排序

### ISSUE THREAD

**Issue by maanrry** [slimkit/thinksns-plus#223]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:
创建话题缺少话题头像，话题状态（启动、禁用）排序

![image](https://user-images.githubusercontent.com/30249193/32156618-7c9c4fcc-bd79-11e7-911c-418ecb8ff47c.png)
脑图：
![image](https://user-images.githubusercontent.com/30249193/32156647-a31a7d90-bd79-11e7-8ac6-0f85e016811d.png)

### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
分步，创建后单独设置。无法一起
