### ISSUE TITLE
【后台】问答模块--话题管理--表单：缺少回答数量，状态（开启/关闭）；排序；编辑（禁用/开启操作）

### ISSUE THREAD

**Issue by maanrry** [slimkit/thinksns-plus#224]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:
表单缺少项：回答数量，状态（开启/关闭）；排序；编辑（禁用/开启操作）

![image](https://user-images.githubusercontent.com/30249193/32156722-07f41046-bd7a-11e7-9ece-afc5103683fb.png)
脑图
![image](https://user-images.githubusercontent.com/30249193/32156728-106fcb98-bd7a-11e7-8f0d-fccdbc621836.png)

### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
话题下没有回答关联，联系天龙修改需求。这个后台需求和前台根本对不上。

**Comment by medz** [comment]
话题下没有回答关联，联系天龙修改需求。这个后台需求和前台根本对不上。
