### ISSUE TITLE
[文档缺失] 文档未对返回参数进行更多说明

### ISSUE THREAD

**Issue by LipYoung** [slimkit/thinksns-plus#229]
![image](https://user-images.githubusercontent.com/15086314/32158746-47e58bc4-bd18-11e7-831b-bb4f9a5bf641.png)

该接口 https://slimkit.github.io/plus-docs/v2/core/users/#获取一个用户
如果传入该参数,和不传入该参数时,返回的数据结构未做详细的说明

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/32159010-7edd32e8-bd19-11e7-87d2-55027fffb476.png)
不传为当前登录用户，如同没有传递 auth 令牌，则判定所有状态为 false。
Thanks.
