### ISSUE TITLE
【系统配置】- 字段类型错误

### ISSUE THREAD

**Issue by Jungle68** [slimkit/thinksns-plus#230]
- TS+ Version: v#.#.#  app version 1.2.0-beta
- PHP Version:
- Database Driver & Version:

### Description:

![image](https://user-images.githubusercontent.com/7939686/32313183-8985eb7e-bf6f-11e7-9930-31f847864b9b.png)

配置接口：本来应该是一个object ,但是现在返回的是一个boolean

### Fixed step:

- [ ] fixed.

**Comment by this-BaiShi** [comment]
部分服务器没更新新的后台，配置以正式服为主
