### ISSUE TITLE
【用户】- 头像修改无效

### ISSUE THREAD

**Issue by Jungle68** [slimkit/thinksns-plus#231]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

修改头像接口成功，但是查看图片未变

### Fixed step:

- [ ] fixed.

**Comment by this-BaiShi** [comment]
设置cdn后，图片会在cdn上会缓存一天，并不能及时更新，这个之后优化

**Comment by medz** [comment]
这个问题之后由我跟进处理。

**Comment by medz** [comment]
@this-BaiShi 我已经把「本地」、「七牛」完成，解决了这两个平台存在不同步头像的问题，最后一个你开发的「oss」你上班处理。

**Comment by this-BaiShi** [comment]
收到~~明天我去看看commit 然后“借鉴“一下
