### ISSUE TITLE
【后台】匿名说明缺少配置和内容

### ISSUE THREAD

**Issue by maanrry** [slimkit/thinksns-plus#234]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:
匿名说明缺少配置和内容

### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/34197907-61ff22d2-e5a3-11e7-9c25-324334ff9a00.png)
已复查，确认修复
