### ISSUE TITLE
【广告位】- 广告持续时间字段有问题啊

### ISSUE THREAD

**Issue by legendarytym** [slimkit/thinksns-plus#236]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

![image](https://user-images.githubusercontent.com/11835710/32484844-3cad3552-c3dc-11e7-838b-e95b47aeb695.png)
看图
@this-BaiShi 

### Fixed step:

- [ ] fixed.

**Comment by this-BaiShi** [comment]
已限制为int类型
