### ISSUE TITLE
[后台] 添加广告位，所有广告图片均没有图片尺寸提醒

### ISSUE THREAD

**Issue by maanrry** [slimkit/thinksns-plus#237]
- [ ] fixed.

**Comment by medz** [comment]
@LipYoung 需要给出所有广告位的具体尺寸方可处理，请回复广告位尺寸。感谢！

**Comment by this-BaiShi** [comment]
- 列表顶部广告 宽375pt x 高187.5pt
- 列表模拟广告 宽262.5pt x 高262.5pt
- 详情页广告 
> 一张图： 宽353.5pt x 高59pt;
> 两张图：宽174.5pt x 高59pt;
> 三张图： 宽111.5pt x 高59pt;
- 启动页广告 宽375pt x 高538pt
