### ISSUE TITLE
[API/v2] 收费文件 GIF 图片达到 200 帧返回模糊图片失败（返回原图）

### ISSUE THREAD

**Issue by Jungle68** [slimkit/thinksns-plus#239]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Fixed step:

- [ ] fixed.

**Comment by boxshadow** [comment]
![qq 20171113150631](https://user-images.githubusercontent.com/8577474/32713457-486d2ce2-c884-11e7-8542-b8a88eae7304.png)

**Comment by medz** [comment]
200 帧的 GIF ？牛逼牛逼。
