### ISSUE TITLE
Undefined constant 'Zhiyi\Plus\VERSION'

### ISSUE THREAD

**Issue by denept** [slimkit/thinksns-plus#241]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

安装提示错误
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.5)
phpunit/phpunit suggests installing phpunit/php-invoker (^1.1)
phpunit/phpunit suggests installing ext-xdebug (*)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Undefined constant 'Zhiyi\Plus\VERSION'

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
```shell
git pull
```

**Comment by ricin123** [comment]
/vendor/slimkit/plus-installer/router.php 中的Zhiyi\Plus\VERSION换成对应的版本数字
