### ISSUE TITLE
【后台-认证管理】筛选待审核后审核了其中一个后列表又刷新成全部的

### ISSUE THREAD

**Issue by peicaichi** [slimkit/thinksns-plus#242]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

筛选待审核后审核了其中一个后列表又刷新成全部的，应还是保持在筛选后的列表

### Steps To Reproduce:

认证管理-筛选“待认证、个人认证”-点击其中一个通过认证-列表页刷新显示了所有的数据，而非筛选后的数据
### Fixed step:

- [x] fixed.

**Comment by medz** [comment]
已审查通过，已完成修复。
