### ISSUE TITLE
【圈子】- 拒绝帖子评论置顶

### ISSUE THREAD

**Issue by legendarytym** [slimkit/thinksns-plus#245]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:
拒绝帖子评论置顶，返回 ..没有权限...

### Steps To Reproduce:
@this-BaiShi 

### Fixed step:

- [ ] fixed.

**Comment by this-BaiShi** [comment]
已查证为初期的脏数据导致
