### ISSUE TITLE
[个人中心 - 设置 - 关于我们] 增加后台配置功能

### ISSUE THREAD

**Issue by LipYoung** [slimkit/thinksns-plus#251]
为了方便授权客户修改该页面.
先修改该功能未管理员在管理后台填写一个网址,
前端使用浏览器打开该网址即可

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/34197191-507c8fb6-e5a0-11e7-9956-d222543b8dba.png)
审查通过，已完成需求开发。
