### ISSUE TITLE
[后台->资讯] 资讯后台添加资讯选择了标签，提交的时候未提交

### ISSUE THREAD

**Issue by zongyanbin** [slimkit/thinksns-plus#260]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:
![qq 20171226104655](https://user-images.githubusercontent.com/11399544/34345450-218fc3b0-ea2a-11e7-965b-d881f2fe5e58.png)

### Description:

咨询模块添加添加咨询信息，然后都填好了点击提交，提示请选中咨询标签~不让保存!
![qq 20171226104655](https://user-images.githubusercontent.com/11399544/34345456-34b73306-ea2a-11e7-9c68-e330738f354d.png)

### Fixed step:

- [ ] fixed.

**Comment by ydxred** [comment]
我也遇到同样的问题

**Comment by huhaophp** [comment]
@zongyanbin @ydxred 
箭头所指是标签分类标题，正确如下图：
![image](https://user-images.githubusercontent.com/15937325/38604045-d7045dee-3da1-11e8-9cbf-8a4461320624.png)
发布资讯先在后台添加标签
![image](https://user-images.githubusercontent.com/15937325/38604110-fbe7bda4-3da1-11e8-8202-59dd8ef77824.png)
