### ISSUE TITLE
composer install 遇到问题，有解决办法吗

### ISSUE THREAD

**Issue by sukeju** [slimkit/thinksns-plus#261]
- Installing slimkit/plus-checkin (1.1.0): Symlinking from packages/slimkit-plus-checkin

  [RuntimeException]
  Symlink from "/data/wwwroot/thinksns-plus/packages/slimkit-plus-checkin" to "/data/wwwroot/thin
  ksns-plus/vendor/slimkit/plus-checkin" failed!

**Comment by medz** [comment]
你删除 vendor 然后重试下，没有这个问题。集成测试也没有问题。

**Comment by sxx20001227** [comment]
删除了vendor还是有报错呢

**Comment by medz** [comment]
cd packages && ls -al 截图发给我

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2018年1月17日，08:24，sxx20001227 <notifications@github.com<mailto:notifications@github.com>> 写道：


删除了vendor还是有报错呢

**Comment by sxx20001227** [comment]
截图在附件里
