### ISSUE TITLE
安装composer时出错 无法安装

### ISSUE THREAD

**Issue by sxx20001227** [slimkit/thinksns-plus#263]
- TS+ Version: v#.#.#
- PHP Version:7.2
- Database Driver & Version:

### Description:

安装时，进入thinksns-plus 目录，执行composer install时，会出现红色报错：
[RuntimeException]
Symlink from “/www/wwwroot/abc.com/thinksns-plus/packages/slimkit-plus-appversion” to “/www/wwwroot/abc.com/thinksns-plus/vendor/slimkit/plus-appversion” failed! 

也有其他人遇到同样的情况，我觉得安装指南里面说得不是很清楚，composer是什么程序呢？此问题如何解决呢？
http://tsplus.zhibocloud.cn/question/476中别人也报告了相同问题

### Steps To Reproduce:

安装时，进入thinksns-plus 目录，执行composer install时，会出现红色报错：
[RuntimeException]
Symlink from “/www/wwwroot/abc.com/thinksns-plus/packages/slimkit-plus-appversion” to “/www/wwwroot/abc.com/thinksns-plus/vendor/slimkit/plus-appversion” failed! 

### Fixed step:

- [ ] fixed.

**Comment by vvsunny** [comment]
同问

**Comment by medz** [comment]
@vvsunny @sxx20001227 请开启 `Symlink ` 函数
