### ISSUE TITLE
后台vue热加载 webpack npm run hot 404

### ISSUE THREAD

**Issue by cdmalcl** [slimkit/thinksns-plus#267]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

npm run hot
package.json:
`"hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --host 0.0.0.0 --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",`

访问：http://192.168.64.2:8080/mypro/public/admin

`Cannot GET /mypro/public/admin`

增加
` --content-base public/
 --content-base mypro/public/`
无效
### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
hot 不代表你可以直接用 node 开启的地址访问，而是静态资源，你依旧需要正常安装 ts+
