### ISSUE TITLE
composer依赖关系不满足alexfloppy/php-apk-parser-php7

### ISSUE THREAD

**Issue by dwdcth** [slimkit/thinksns-plus#274]
- TS+ Version: master
- PHP Version: 7.1.15
- Database Driver & Version:

### Description:
composer安装依赖不满足

 Problem 1
    - Installation request for slimkit/plus-appversion 1.7.0 -> satisfiable by slimkit/plus-appversion[1.7.0].
    - slimkit/plus-appversion 1.7.0 requires alexfloppy/php-apk-parser-php7 ^2.0 -> no matching package found.

### Steps To Reproduce:
使用composer create-project zhiyicx/thinksns-plus就会出现

### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
因为 alexfloppy/php-apk-parser-php7 这个库的作者删除了之前发布的所有 tag 。。。。无奈！会在下一个预览版中修复这个问题

**Comment by zanjs** [comment]
@medz 现在安装不了 只能坐等了吗？

**Comment by medz** [comment]
本周内修复

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2018年3月21日，15:11，zan <notifications@github.com<mailto:notifications@github.com>> 写道：


@medz<https://github.com/medz> 现在安装不了 只能坐等了吗？

**Comment by xhrgbczc** [comment]
处理好了吗

**Comment by liqunx** [comment]
没办法了，等了几天，还没修复，只能把 `\thinksns-plus\packages\slimkit-plus-appversion\composer.json`文件第8行改为`"alexfloppy/php-apk-parser-php7": "*",`;暂时跳过这个bug

**Comment by medz** [comment]
已经修复了… 上周就修复了的

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2018年3月28日，16:45，xulq <notifications@github.com<mailto:notifications@github.com>> 写道：


没办法了，等了几天，还没修复，只能把 \thinksns-plus\packages\slimkit-plus-appversion\composer.json文件第8行改为"alexfloppy/php-apk-parser-php7": "*",;暂时跳过这个bug
