### ISSUE TITLE
后台 CDN 获取已选择的 CDN 路由单词拼写错误！

### ISSUE THREAD

**Issue by Wanchaochao** [slimkit/thinksns-plus#286]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:
![image](https://user-images.githubusercontent.com/18748601/38800066-da4bca32-4198-11e8-946a-3fc86e37ae1f.png)

/routes/admin.php  line:98
是不是单词拼错了,但是还没有发现有报错

### Fixed step:

- [x] fixed.

**Comment by medz** [comment]
是的，单词拼写错误～感谢！😄

**Comment by medz** [comment]
selected
