### ISSUE TITLE
web版本的前端都没有了，只有一个简单的H5页面，这怎么用啊？？？

### ISSUE THREAD

**Issue by xhb** [slimkit/thinksns-plus#291]

**Comment by medz** [comment]
简单的？你怕是看错了哟。。。

**Comment by xhb** [comment]
开源版的web前端怎么安装？

```
https://github.com/zhiyicx/plus-component-pcos
```
这个项目没有安装说明。。

h5 页面不方面写文档post。

**Comment by medz** [comment]
pc 的话，请咨询商务，或者询问 @HHHCODE ，关于 pc 的讨论请在 https://github.com/zhiyicx/plus-component-pcos 进行。感谢！
