### ISSUE TITLE
{type: bug, version: ts+}: ts+后台已经安装到本机了，请问下如何将ThinkSNS Plus PC安装到本机？

### ISSUE THREAD

**Issue by chengwenya** [slimkit/thinksns-plus#296]
## 基本信息

版本：`ts+`

## 重现步骤

ts+后台已经安装到本机了，请问下如何将ThinkSNS Plus PC安装到本机？

## 补充说明（可选）

PHP 版本：
数据库类型：
数据库版本：

**Comment by medz** [comment]
暂时 pc 无法安装
