### ISSUE TITLE
上传接口返回404，无法上传图片

### ISSUE THREAD

**Issue by cruelwolfking** [slimkit/thinksns-plus#303]
**上传接口出错**
接口地址：/api/v2/files/uploaded/5b1c04fab3f7b5e64e59f9838e4b93ac
返回错误：`exception
:
"Symfony\Component\HttpKernel\Exception\NotFoundHttpException"
file
:
"F:\Project\thinksns-plus\vendor\laravel\framework\src\Illuminate\Foundation\Application.php"
line
:
939
message
:
""`

**Comment by medz** [comment]
你这个错误返回根本看不出问题呀

**Comment by medz** [comment]
而且，这个是检查 hash 的接口，404 也是属于正常情况表示文件不存在，请上传的意思，还有一种情况是接口不存在，建议你阅读文档
