### ISSUE TITLE
[PC][Cors] 使用原生支付宝在 PC 进行充值后金额不到账！！！

### ISSUE THREAD

**Issue by medz** [slimkit/thinksns-plus#309]
**Describe the bug**
如题

**To Reproduce**
1. 进入 pc
2. 点击我的钱包
3. 点击充值
4. 付款
5. 余额毫无变化！！！

**Comment by medz** [comment]
@boxshadow 所以，请问是修复了吗？

**Comment by boxshadow** [comment]
@medz 修复了
