### ISSUE TITLE
php artisan migrate报错

### ISSUE THREAD

**Issue by 1377195627** [slimkit/thinksns-plus#57]
[Illuminate\Database\QueryException]                                                            
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key le  
  ngth is 767 bytes (SQL: alter table `verify_codes` add index `verify_codes_account_index`(`acc  
  ount`))                                                                                         
                                                                                                  
  [PDOException]                                                                                  
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key le  
  ngth is 767 bytes 

修改AppServiceProvider.php添加
    Schema::defaultStringLength(191);
无效，改my.cnf也无效

mariadb版本10.1.24

**Comment by medz** [comment]
该版本是建立在 mysql 5.6 的，因为长度问题，在 5.6 下我们程序必须把 varchar 字段最长限制在 191 个，造成了一些需要稍微长一点的索引字段储存不足。如同文档中说的，建议用 mysql 5.7 或者 pgsql

**Comment by lain1936** [comment]
https://laravel-china.org/topics/3852/string-length-problem-caused-by-character-encoding-change-in-laravel-54-mysql-database

https://stackoverflow.com/a/39750202

**Comment by medz** [comment]
@lain1936 请仔细看文章解决方法，这个方法是减短 VARCHAR 的长度，原本我需要 255 ，仙子啊只能是 191 ，所以我们选择不妥协，需求是 255 就是 255，而不是减少到 191 ，程序里面存 VARCHAR 字段的时候不可能到处手动控制在 191 之内。

**Comment by lain1936** [comment]
不是，确实不应该设置成utf8mb4的191，
可以在config/database.php, 改成utf8（上限为255） , 至于需要utf8mb4的表，另外再看是否有索引调整
或者是
按照stackoverflow的那个答案，对<=5.6的mysql或者mariadb<=10.1.*  设置ROW_FORMAT=DYNAMIC
以及其他的配置（我没尝试 只是用的utf8的设置）

不是妥协不妥协的问题啊 有可能会有之前的mysql版本在跑，统一管理；又或者是因为目前一些快速搭建脚本或服务器环境只有5.6下的mysql或者10.1的mariadb

**Comment by medz** [comment]
那 emoji 怎么办？因为面向移动端为主，用户输入 emoji 不可能过滤。

**Comment by medz** [comment]
而且，我们也是想直接支持 emoji，你说的问题完全不是问题，可以使用 `laradock` 搭建环境，也可以自己配置高版本环境。

**Comment by lain1936** [comment]
emoji的话， 用户名这种需要索引的用不着那么长的 可以128什么的，
其他大部分内容不需要索引，标题有可能会有emoji使用场景
