### ISSUE TITLE
功能建议：使用JWT和element-dashboard

### ISSUE THREAD

**Issue by lain1936** [slimkit/thinksns-plus#58]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:
1.  前后端分离使用jwt的token验证，可以更好的与其他的服务集成，或者考虑将其作为可选配置
2.  既然使用vue，可以考虑使用饿了么的组件，外观和文档都不错

另外: 请问下开源的版本和官网上预售的各种版本是什么关系？
是否预售版仅是额外的商业定制，而开源出的也没有开源协议外的其他限制？

**Comment by medz** [comment]
1. 目前v2 API 中是会推出 基于 OAuth2 的服务端支持。
2. 目前不考虑 Element UI 组件，后台 UI 看是否有需求重构再选择 UI 框架。
开源版本遵循 APache-2.0 协议，开源和商业授权其实并不冲突的。你可以 fork 后进行定制，但是一定要遵循 Apache-2.0 协议，如果你想做私有产品产品，并不想遵循开源协议要求，可以联系商务购买产品的商业授权。
