### ISSUE TITLE
php artisan migrate报错

### ISSUE THREAD

**Issue by 121753961** [slimkit/thinksns-plus#61]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

[Illuminate\Database\QueryException]                                         
  SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_s  
  chema.tables where table_schema = forge and table_name = migrations)

                                            
  [PDOException]                             
  SQLSTATE[HY000] [2002] Connection refused

### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
你设置问题，应该是你数据库不存在。

**Comment by 121753961** [comment]
可以请教一下要怎么设置吗，没有用过LaraDock。

**Comment by medz** [comment]
@121753961 就是创建一个空数据库。。。

**Comment by 121753961** [comment]
@medz  
**数据库里已经新建了个  plus  的数据库 执行php artisan migrate  还是报错**
麻烦再帮我看一下，我的 .env配置如果
APP_NAME=ThinkSNS+
APP_ENV=local
APP_KEY=base64:tJHsTmPBAaCP0MBuoCbJAHYMnT3giqkxW2xS3TBe8NE=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=plus
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=null
PUSHER_APP_KEY=null
PUSHER_APP_SECRET=null

**数据库里已经新建了个  plus  的数据库 执行php artisan migrate  还是报错**
[Illuminate\Database\QueryException]                                         
  SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from inform  
  ation_schema.tables where table_schema = plus and table_name = migrations)   
                                                                               
                                                    
  [PDOException]                                    
  SQLSTATE[HY000] [2002] No such file or directory
