### ISSUE TITLE
后台问题

### ISSUE THREAD

**Issue by 1377195627** [slimkit/thinksns-plus#62]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

安装教程种的输入 {APP_URL}/admin 进入后台
然而public下压根就没admin这货啊

**Comment by medz** [comment]
控制台截图看下

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2017年6月30日，14:31，1377195627 <notifications@github.com<mailto:notifications@github.com>> 写道：


  *   TS+ Version: v#.#.#
  *   PHP Version:
  *   Database Driver & Version:

Description:

安装教程种的输入 {APP_URL}/admin 进入后台
然而public下压根就没admin这货啊

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/27723817-6dba6436-5da1-11e7-9690-0c7333f6ac68.png)
有呀，您看。

**Comment by 1377195627** [comment]
![image](https://user-images.githubusercontent.com/8142265/27723893-cc75bc00-5da1-11e7-9320-c370f0b929cd.png)
问题在于我现在打不开，时不时就会这样,然而我服务器上另外一个网站很正常
这是之前的截图
![image](https://user-images.githubusercontent.com/8142265/27723946-1346c7a0-5da2-11e7-9cae-92f582f503d4.png)

**Comment by medz** [comment]
额～你这个是 500 错误～

**Comment by medz** [comment]
应该是你环境问题，或者php函数禁用～

**Comment by 1377195627** [comment]
什么函数

**Comment by medz** [comment]
你开启 xdebug 页面上会自动提示的。

**Comment by 1377195627** [comment]
怎么开

**Comment by medz** [comment]
-。-！！！安装php拓展

**Comment by 1377195627** [comment]
又正常了
![image](https://user-images.githubusercontent.com/8142265/27725007-03bd5894-5da7-11e7-9999-3643b0ba778e.png)
为何首页只有这么几个字，

![image](https://user-images.githubusercontent.com/8142265/27725029-15de02ee-5da7-11e7-8930-51f61cd95387.png)
后台
而且xdebug好像远程不好弄吧

**Comment by medz** [comment]
在 `php.ini` 打开错误显示。

**Comment by 1377195627** [comment]
本来就是开了的

**Comment by medz** [comment]
很明显，你没有开，你开了不会只返回 http 状态500，还会返回错误消息。

**Comment by 1377195627** [comment]
![image](https://user-images.githubusercontent.com/8142265/27731307-f7d84ec2-5dbe-11e7-8c09-1e1b705cf683.png)

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/27731348-2a5dc39a-5dbf-11e7-8d95-9e11d95f2392.png)
改为 E_ALL

**Comment by 1377195627** [comment]
还是那样，没有

**Comment by medz** [comment]
那说明没有生效。

**Comment by 1377195627** [comment]
我都直接重启了

**Comment by medz** [comment]
如果生效，不会只返回 http status code 的～真的。。。

**Comment by 1377195627** [comment]
跟https有没有原因，http因为没备案访问不了

**Comment by medz** [comment]
没关系的哟。

**Comment by 1377195627** [comment]
你们的安装教程要改改啊，搞了半天居然因为storage和bootstrap没权限

**Comment by medz** [comment]
🤣欢迎 PR 哟。

**Comment by medz** [comment]
毕竟 ThinkSNS Plus 不再是 所谓的开箱即用程序了。很多时候没法面面俱到。

**Comment by 1377195627** [comment]
咋只有一个后台啊，主体部分呢

**Comment by medz** [comment]
拓展包

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2017年6月30日，21:15，1377195627 <notifications@github.com<mailto:notifications@github.com>> 写道：


咋只有一个后台啊，主体部分呢

**Comment by 1377195627** [comment]
哪个扩展包

**Comment by medz** [comment]
例如 `zhiyicx/plus-component-web` 你可以搜 `plus component`

**Comment by 1377195627** [comment]
这货我装了，还是没有啊

**Comment by lain1936** [comment]
plus-component-web的说明不是很清楚
composer require zhiyicx/plus-component-web
然后在plus-component-web目录下执行yarn dev生成dist
然后在主目录执行php artisan package:handle h5 link或者是publish将组件的dist发布到public文件夹下
然后在地址栏后面加上/web查看效果

有些小问题
1 验证码没有配置阿里大于的直接在后台查看
2 你需要在后台勾选feed.post权限，才能发共享（和资讯？）
3 软连接public\storage到 storage\app\public才能看到上传的图片, windows下需要管理员cmd运行mklink /d
4 （windows下）web中vue的图片路径好像有问题baseUrl = url + '/zhiyi/h5/';  resolveImage去掉重复的image,webpack去掉重复的../

**Comment by medz** [comment]
@lain1936 
1. 验证码默认只记录，因为你没有配置发送驱动。
2. 安装应用后应该管理员手动后台勾选权限，处于权限控制考虑。
3. Laravel 提供了 `php artisan storage:link` 来吧 `storage/app/public` 软链到 `public/storages`
4. @boxshadow 你看下。
