### ISSUE TITLE
bug 上传图片

### ISSUE THREAD

**Issue by sucof** [slimkit/thinksns-plus#64]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

在编辑资讯的配图中，存在api/v1/storages/task 401 (Unauthorized)错误，后台使用root用户已经勾选了storage-create权限。

### Steps To Reproduce:

在http://localhost/admin#/package/0中点击编辑资讯，然后点击配图，出现授权失败错误

### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
咨询正在适配新版本的 file with 请等待新版。
