### ISSUE TITLE
执行php artisan migrate 还是报错

### ISSUE THREAD

**Issue by 121753961** [slimkit/thinksns-plus#65]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

@medz
数据库里已经新建了个 plus 的数据库 执行php artisan migrate 还是报错
麻烦再帮我看一下，我的 .env配置如果
APP_NAME=ThinkSNS+
APP_ENV=local
APP_KEY=base64:tJHsTmPBAaCP0MBuoCbJAHYMnT3giqkxW2xS3TBe8NE=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost

DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=plus
DB_USERNAME=root
DB_PASSWORD=

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=null
PUSHER_APP_KEY=null
PUSHER_APP_SECRET=null

数据库里已经新建了个 plus 的数据库 执行php artisan migrate 还是报错
[Illuminate\Database\QueryException]
SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from inform
ation_schema.tables where table_schema = plus and table_name = migrations)

[PDOException]
SQLSTATE[HY000] [2002] No such file or directory

**Comment by medz** [comment]
你把 `localhost` 改为 `127.0.0.1` 试一下

**Comment by 121753961** [comment]
@medz  试过了还是不行

**Comment by medz** [comment]
你装 `php_pdo` 和 `php_pdo_mysql` 拓展了吗？

**Comment by medz** [comment]
你可以百度下 `SQLSTATE[HY000] [2002] No such file or directory` 这个并非 Plus 程序问题哟。

**Comment by 121753961** [comment]
@medz 
我用的是  Laradock 进行部署程序 还要单独装 php_pdo 和 php_pdo_mysql 拓展了吗？

**Comment by medz** [comment]
你用的  Laradock ？你应该了解 docker 容器之间的通信哟，`DB_HOST` 设置为 `mysql` 这是 `mysql` 容器向 `workspace` 暴露的 `host`。

**Comment by medz** [comment]
mysql 暴露的 host 在 Laradock 文档中有说明的哟 [http://laradock.io/getting-started/#usage](http://laradock.io/getting-started/#usage) 你看下。

**Comment by medz** [comment]
```
DB_HOST=mysql
```

**Comment by medz** [comment]
![image](https://user-images.githubusercontent.com/5564821/27813060-d12e0e94-60a5-11e7-97c0-dceb6819d577.png)
给你一个运行在 Laradock 配置参考。

**Comment by medz** [comment]
或者你参考下 Plus 根下的 `.travis.yml` 看我们的持续集成测试，目前测试范围在 `mysql` 和 `pgsql`

**Comment by 121753961** [comment]
@medz   非常感谢终于可以了，建议把这个设置更新到你们那个安装部署完说明里去。

**Comment by medz** [comment]
@121753961 好的，在 plus 的安装文档中描述 Laradock 安装部分比较笼统，后续我们会持续完善文档，感谢。
