### ISSUE TITLE
api不管是v1还是v2获取普通用户的信息的扩展信息为空

### ISSUE THREAD

**Issue by 1377195627** [slimkit/thinksns-plus#69]
api不管是v1还是v2获取普通用户的信息，扩展信息都是空的
v1获取输出的json
![image](https://user-images.githubusercontent.com/8142265/27898379-5d39bb7c-61eb-11e7-9326-c0f8d6b88a13.png)
v2获取输出的json
![image](https://user-images.githubusercontent.com/8142265/27899272-29ede5b4-61ef-11e7-993c-6c3c068c9bb2.png)

**Comment by medz** [comment]
确认下该用户是否设置了拓展信息？

**Comment by medz** [comment]
拓展信息不会返回没有设置的信息的。

**Comment by 1377195627** [comment]
在后台直接注册的账号，没法设置，而且好像没法获取用户的用户组？而且就算是root也好像获取不到用户组

**Comment by medz** [comment]
目前没有需要用到用户组的地方。所以没有，后台注册的账户是没有拓展资料的。

**Comment by medz** [comment]
设置资料参考 profile 表。

**Comment by 1377195627** [comment]
用户权限也不能获取？

**Comment by medz** [comment]
权限可以直接验证，但是没有直接获取权限列表的地方。
