### ISSUE TITLE
消息-置顶审核

### ISSUE THREAD

**Issue by legendarytym** [slimkit/thinksns-plus#73]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

消息-置顶审核   暂无数据（和消息中的点赞、评论一样的消息）

### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
这个是啥意思？

**Comment by legendarytym** [comment]
@medz 
![2](https://user-images.githubusercontent.com/11835710/28000418-437fef38-6558-11e7-9d25-725539dbbfbc.jpg)

**Comment by medz** [comment]
正在设计新的接口。
