### ISSUE TITLE
The Mix manifest does not exist

### ISSUE THREAD

**Issue by 1459416736** [slimkit/thinksns-plus#79]
- TS+ Version: v1.0.0-alpha.4
- PHP Version:7.1
- Database Driver & Version:5.7

### Description:
ErrorException:The Mix manifest does not exist
我手动安装了plus-component-web 组件
执行http://域名/web就会出现上面的错误

### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
yarn dist

**Comment by 1459416736** [comment]
@medz 我在plus-component-web目录下执行了npm run dist 在dist 目录下也生成了文件，但是还会出现与上面一样的错误
ErrorException
The Mix manifest does not exist. (View: /home/vagrant/Code/zhenai/vendor/zhiyicx/plus-component-web/views/index.blade.php

**Comment by medz** [comment]
你应该还没有发布静态文件吧，进入 plus 目录执行 `php artisan package:handle h5 publish`

**Comment by 1459416736** [comment]
plus-component-web 下的composer.json 文件里依赖包zhiyicx/plus-component-news版本是1.0的，没法执行install

**Comment by medz** [comment]
按照 `zhiyicx/plus-component-news` 安装即可。
