### ISSUE TITLE
首页无法显示

### ISSUE THREAD

**Issue by sunnycn2013** [slimkit/thinksns-plus#80]
- TS+ Version: thinkssnsplus+
- PHP Version: php 7.1.7
- Database Driver & Version: mysql  5.7

### Description:
  按照  `https://github.com/slimkit/thinksns-plus/blob/master/docs/get-started/installed.md` 的安装流程安装完成后，进入到public目录，发现首页无法显示

首页无法显示

### Steps To Reproduce:

![85bdedda-8b7e-43f2-be22-77d9a921d505](https://user-images.githubusercontent.com/3810388/28061519-786a341e-665d-11e7-8b8a-0be45a60fb45.png)

### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
这个就是首页～

**Comment by sunnycn2013** [comment]
那为啥没有内容啊？怎们进入对应的页面，有内容的页面

**Comment by medz** [comment]
ThinkSNS plus 核心只提供 API，显示数据的都是客户端，你可以看下 `zhiyicx/plus-component-web` 等拓展包，提供视图。

**Comment by medz** [comment]
你可以执行 `composer require zhiyicx/plus-component-web` 得到一个 h5.

**Comment by medz** [comment]
参考 https://github.com/slimkit/plus-component-web

**Comment by medz** [comment]
或者去 https://github.com/zhiyicx 账户下，得到更多的拓展包。

**Comment by sunnycn2013** [comment]
```
社交系统ThinkSNS 最新版本ThinkSNS+将于7月15日正式发布开源版本，开源版包含：web+H5。同时发布Android APP和iOS APP，届时将会公开体验二维码，敬请期待，欢迎下载使用。我们将告别内测阶段，正式对外发布。有任何问题可以咨询官网QQ3298713109，电话18108035545（同微信）；028-82884828，详情☞http://www.thinksns.com/zx/reader.php?id=127
```

我想了解下，你们这个仓库目前还没有开源吗，这个15号开源的仓库是这个吗  `https://github.com/slimkit/thinksns-plus`  吗？

**Comment by medz** [comment]
一直是开源的，发布是指对外发布。。。代码公开和发布是两码事哟。

**Comment by medz** [comment]
发布只是版本发布。。。完了，又要科普语文。。。额～你百度“发布”是指啥吧～发布不是你理解的「发布=公开」

**Comment by sunnycn2013** [comment]
我想问下 “开源版包含：web+H5”    这个最新的版本是否已经放出来了，还是要等到15号才会在GitHub上看到

**Comment by medz** [comment]
一直在 github 上。。所谓发布是指发布正式版，现在是测试版。。。一个程序版本发布。。。。

**Comment by sunnycn2013** [comment]
我就想问下 “开源版包含：web+H5” 这个对应的源码github 上有吗，在哪？

**Comment by medz** [comment]
我刚不是回复过了吗？
