### ISSUE TITLE
安装的测试版本错误挺多，没法测哦

### ISSUE THREAD

**Issue by 1459416736** [slimkit/thinksns-plus#81]
- TS+ Version: v1.0.0-alpha.4
- PHP Version:7.1
- Database Driver & Version:5.7

### Description:

im_users' doesn't exist
followings' doesn't exist
是不是你们删除了数据库表，没有删除代码哦
### Fixed step:

- [x] 注册抛出异常错误.
- [x] v1 获取用户列表接口 follow 相关代码错误。

**Comment by medz** [comment]
你好，能给出 php 具体错误截图么？

**Comment by 1459416736** [comment]
@medz 这个是注册时候的错误
[2017-07-13 02:22:38] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Zhiyi\Plus\Http\Controllers\APIs\V1\RuntimeException' not found in /home/vagrant/Code/zhenai/app/Http/Controllers/APIs/V1/AuthController.php:175
Stack trace:
#0 [internal function]: Zhiyi\Plus\Http\Controllers\APIs\V1\AuthController->Zhiyi\Plus\Http\Controllers\APIs\V1\{closure}()

**Comment by medz** [comment]
@1459416736 Stack trace 可否剩下的部分给我呢，我需要看下允许轨迹。

**Comment by medz** [comment]
按照目前你给出的错误，最新的 alpha.4 中是没有的，RuntimeException 异常这里一直没有使用过。

**Comment by 1459416736** [comment]
@medz 我看到了你是新加的代码引起的问题，你的代码throw new RuntimeException('Failed to get the defined user group.');是这样的
应该改成这样 throw new \RuntimeException('Failed to get the defined user group.');
没有引入命名空间

**Comment by medz** [comment]
好的，我看到了，我们这边开发人员的失误。@This-Baishi 以后注意，修复后 fixed 这个 issues。

**Comment by 1459416736** [comment]
@medz 登陆报错如下
Next Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'zhenai.followings' doesn't exist (SQL: select * from `followings` where `user_id` = 2 and `following_user_id` = 2) in /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Database/Connection.php:647
Stack trace:
#0 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#2 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1710): Illuminate\Database\Connection->select('select * from `...', Array, true)
#3 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1695): Illuminate\Database\Query\Builder->runSelect()
#4 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(462): Illuminate\Database\Query\Builder->get(Array)
#5 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(446): Illuminate\Database\Eloquent\Builder->getModels(Array)
#6 /home/vagrant/Code/zhenai/app/Http/Controllers/APIs/V1/UserController.php(97): Illuminate\Database\Eloquent\Builder->get()
#7 [internal function]: Zhiyi\Plus\Http\Controllers\APIs\V1\UserController->get(Object(Illuminate\Http\Request))
#8 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#9 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('get', Array)
#10 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Zhiyi\Plus\Http\Controllers\APIs\V1\UserController), 'get')
#11 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#12 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Routing\Route->run()
#13 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure), '60', '1')
#19 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/Router.php(576): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/Router.php(535): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#23 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/Router.php(513): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#24 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#25 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#26 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#40 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#41 /home/vagrant/Code/zhenai/public/index.php(52): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))

**Comment by medz** [comment]
@1459416736 运行树已收到，目前确定这个 issue 提交了 2 bug，正在修复。

**Comment by 1459416736** [comment]
@medz  你好，请教个问题plus-component-im 数据库表创建的命令是什么？

**Comment by medz** [comment]
@1459416736 
安装：`php artisan package:handle im install`
卸载：`php artisan package:handle im remove`

其实，你可以直接输入 `php artisan package:handle` 查看所有安装包的支持命令。

你也可以输入 `php artisan package:handle im`  查看 im 包的支持命令，其他包也是同理。

**Comment by 1459416736** [comment]
@medz 
你说的这个是你们新组件的安装方法我是知道的，而plus-component-im 是旧版本的结构，不存在package:handle ，所以不知道

**Comment by medz** [comment]
这个包大了一个新 tag 的 是 2.0 你升级到 2.0 就可以用。

Seven Du <shiweidu@outlook.com<mailto:shiweidu@outlook.com>>

在 2017年7月13日，11:03，1459416736 <notifications@github.com<mailto:notifications@github.com>> 写道：


@medz<https://github.com/medz>
你说的这个是你们新组件的安装方法我是知道的，而plus-component-im 是旧版本的结构，不存在package:handle ，所以不知道

**Comment by 1459416736** [comment]
ok,thinks

**Comment by medz** [comment]
@1459416736 你在这个 issue 提交的 bug都已修复，我就关闭了。有问题可以继续提问的。
