### ISSUE TITLE
UserController.php(268)行 followings 错误

### ISSUE THREAD

**Issue by 1459416736** [slimkit/thinksns-plus#82]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:
```
Next Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'zhenai.followings' doesn't exist (SQL: select * from `followings` where `following_user_id` = 2 and `created_at` > 1970-01-01 00:00:01 order by `id` desc) in /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Database/Connection.php:647
Stack trace:
#0 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#2 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1710): Illuminate\Database\Connection->select('select * from `...', Array, true)
#3 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1695): Illuminate\Database\Query\Builder->runSelect()
#4 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(462): Illuminate\Database\Query\Builder->get(Array)
#5 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(446): Illuminate\Database\Eloquent\Builder->getModels(Array)
#6 /home/vagrant/Code/zhenai/app/Http/Controllers/APIs/V1/UserController.php(268): Illuminate\Database\Eloquent\Builder->get()
#7 [internal function]: Zhiyi\Plus\Http\Controllers\APIs\V1\UserController->flushMessages(Object(Illuminate\Http\Request))
#8 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#9 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('flushMessages', Array)
#10 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Zhiyi\Plus\Http\Controllers\APIs\V1\UserController), 'flushMessages')
```

### Fixed step:

- [x] fixed.

**Comment by medz** [comment]
额，小小建议，你应该看下markdown的语法。

**Comment by medz** [comment]
@1459416736 同时建议使用 v2 接口，v1 在 alpha版本结束后就会被删除的。

**Comment by medz** [comment]
@1459416736 v1 接口是满足内部开发的原型接口，v2 开始提供对外的规范接口。

**Comment by 1459416736** [comment]
@medz 主要是安装的你们plus-component-web 看看效果，里面的接口是采用的v1引起的

**Comment by this-BaiShi** [comment]
核心近期部分改动较大，正在对v1接口进行兼容处理

**Comment by medz** [comment]
@1459416736 了解，这个包确实是在一直使用 v1 接口

**Comment by 1459416736** [comment]
### `在请教个问题如下：
``
`2017-07-13 06:27:06] local.ERROR: GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to 127.0.0.1 port 9900: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /home/vagrant/Code/zhenai/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186
Stack trace:
#0 /home/vagrant/Code/zhenai/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /home/vagrant/Code/zhenai/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /home/vagrant/Code/zhenai/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /home/vagrant/Code/zhenai/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /home/vagrant/Code/zhenai/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /home/vagrant/Code/zhenai/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /home/vagrant/Code/zhenai/vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 /home/vagrant/Code/zhenai/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 /home/vagrant/Code/zhenai/vendor/guzzlehttp/guzzle/src/Middleware.php(57): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 /home/vagrant/Code/zhenai/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 /home/vagrant/Code/zhenai/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 /home/vagrant/Code/zhenai/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 /home/vagrant/Code/zhenai/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Client->requestAsync('post', Object(GuzzleHttp\Psr7\Uri), Array)
#13 /home/vagrant/Code/zhenai/vendor/zhiyicx/plus-component-im/src/Service/IM/Service.php(297): GuzzleHttp\Client->request('post', '/users', Array)
#14 /home/vagrant/Code/zhenai/vendor/zhiyicx/plus-component-im/src/Service/IM/Service.php(142): Zhiyi\Component\ZhiyiPlus\PlusComponentIm\Service\IM\Service->request()
#15 /home/vagrant/Code/zhenai/vendor/zhiyicx/plus-component-im/src/Controllers/ImController.php(54): Zhiyi\Component\ZhiyiPlus\PlusComponentIm\Service\IM\Service->__call('userspost', Array)
#16 [internal function]: Zhiyi\Component\ZhiyiPlus\PlusComponentIm\Controllers\ImController->getImAccount(Object(Illuminate\Http\Request))
#17 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#18 /home/vagrant/Code/zhenai/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('getImAccount', Array)

**Comment by medz** [comment]
@1459416736 这个是因为你没有安装 im 服务器，你可以只依赖 im 包，但是不开启 im 服务，这个问题是请求 im 服务器 失败。安装 im 包后在后台设置的。

**Comment by 1459416736** [comment]
@medz 你说

> **这个是因为你没有安装 im 服务器**
指的是什么？这个127.0.0.1:9900就是我在后台设置的，本身是120.0.0.1:9900

**Comment by medz** [comment]
@1459416736 
![image](https://user-images.githubusercontent.com/5564821/28154871-92107798-67de-11e7-90d8-ff897db8d730.png)

**Comment by medz** [comment]
https://github.com/slimkit/plus-component-im

**Comment by 1459416736** [comment]
@medz 哦，我看到了你们官网是需要整个产品的授权，im 服务是不能单独购买的是吧，哎，花了点时间研究看效果，结果跑不起来哈

**Comment by medz** [comment]
@1459416736 im 不影响，不用就行了。

**Comment by 1459416736** [comment]
@medz 呵呵，把im组件删除了有报不完的错哈

**Comment by medz** [comment]
plus-component-web 依赖 im 只是读取配置，看是否开启了 im，没开启也不影响。

**Comment by medz** [comment]
@1459416736 刚我问了下，前端在刷新页面的时候会去请求im口令，忘记写判读了，因为这边的开发需求是，有 im 有即时聊天，没有im就关闭。等待更新。
或者你去 https://github.com/slimkit/plus-component-web 提交一个 issue。
