### ISSUE TITLE
【首页】自己发布的长文字付费刷新首页，列表页显示变短了一截 

### ISSUE THREAD

**Issue by peicaichi** [slimkit/thinksns-plus#83]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

自己发布的长文字付费刷新首页，列表页显示变短了一截 ，后台只返回了50个字，
### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
哪里不对？付费文字，后面内容没权限。php无法完整的判断字符族。付费后可看后面内容。

**Comment by peicaichi** [comment]
自己查看自己的发布

**Comment by this-BaiShi** [comment]
已在列表里做判断
