### ISSUE TITLE
【消息-置顶审核】当申请人的评论被删除后，审核通知显示的是该动态被删除 

### ISSUE THREAD

**Issue by peicaichi** [slimkit/thinksns-plus#84]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

当申请人的评论被删除后，置顶审核显示的是该动态被删除 

### Fixed step:

- [ ] fixed.

**Comment by this-BaiShi** [comment]
删除评论时关联删除了申请
