### ISSUE TITLE
【我-钱包-明细】支出的明细详情里，收款人全是显示自己

### ISSUE THREAD

**Issue by peicaichi** [slimkit/thinksns-plus#85]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

支出的明细详情里，收款人全是显示自己，收入明细里，付款人也全显示自己
### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
这个也是服务端问题？这是app 问题好不好。

**Comment by peicaichi** [comment]
后台未返回收款人和付款人
