### ISSUE TITLE
【我-钱包-明细-支出】申请置顶正在审核中，明细显示的是交易成功

### ISSUE THREAD

**Issue by peicaichi** [slimkit/thinksns-plus#86]
- TS+ Version: v#.#.#
- PHP Version:
- Database Driver & Version:

### Description:

申请置顶正在审核中，明细显示的是交易成功
### Fixed step:

- [ ] fixed.

**Comment by medz** [comment]
这个没问题，扣款成功，申请提现从账户扣款成功。如果审核未通过还有一个增加积分的明细。哪里不对了？
